apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello
spec:
  values:
    environment: staging
    image:
      tag: 1.0.11 # {"$imagepolicy": "data:staging-hello:tag"}
      automation:
        semver:
          expr: 1.x.x
