apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pipeline
spec:
  values:
    image:
      tag: 0.1.2 # {"$imagepolicy": "data:pipeline:tag"}
      automation:
        semver:
          expr: x.x.x
