apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pipeline
spec:
  values:
    environment: staging
    image:
      tag: 0.1.3 # {"$imagepolicy": "data:staging-pipeline:tag"}
      automation:
        semver:
          expr: x.x.x
