apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: critical
spec:
  values:
    environment: production
    image:
      tag: 0.1.3 # {"$imagepolicy": "data:production-critical:tag"}
      automation:
        semver:
          expr: 1.x.x
