apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello
spec:
  values:
    environment: production
    image:
      tag: 1.0.10 # {"$imagepolicy": "data:production-hello:tag"}
      automation:
        semver:
          expr: 1.x.x
