apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: critical
spec:
  values:
    hosts:
    - critical.production.eun
    - critical.data.svc.cluster.local
    image:
      tag: 0.1.3 # {"$imagepolicy": "data:production-eun-critical:tag"}
      automation:
        semver:
          expr: 1.x.x
