apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pipeline
spec:
  values:
    hosts:
    - pipeline.production.eun
    - pipeline.data.svc.cluster.local
    image:
      tag: 0.1.3 # {"$imagepolicy": "data:production-eun-pipeline:tag"}
