{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "api.name" . }}
  labels:
    app: {{ template "api.name" . }}
    release: {{ .Release.Name }}
    tier: "cluster"
spec:
  endpoints:
  - scheme: http
    targetPort: http
    interval: 5s
  jobLabel: {{ include "api.name" . }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ include "api.name" . }}
  {{ end }}
