apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: critical
spec:
  values:
    hosts:
    - critical.staging.eun
    - critical.data.svc.cluster.local
    image:
      tag: 1.1.0 # {"$imagepolicy": "data:staging-eun-critical:tag"}
    dark:
      enabled: false
      image:
        tag: 2.0.0 # {"$imagepolicy": "data:staging-eun-critical-dark:tag"}
