apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: critical
spec:
  values:
    hosts:
    - critical.staging.eun
    - critical.data.svc.cluster.local
    image:
      automation:
        semver:
          expr: 1.x.x
      tag: 1.0.0 # {"$imagepolicy": "data:staging-eun-critical:tag"}
    dark:
      enabled: true
      image:
        automation:
          semver:
            expr: 2.x.x
        tag: 2.1.0 # {"$imagepolicy": "data:staging-eun-critical-dark:tag"}
