apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello
spec:
  values:
    hosts:
    - hello.staging.eun
    - hello.data.svc.cluster.local
    image:
      tag: 1.0.11 # {"$imagepolicy": "data:staging-eun-hello:tag"}
