apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pipeline
spec:
  values:
    hosts:
      - pipeline.staging.eun
      - pipeline.data.svc.cluster.local
    image:
      tag: 1.0.0 # {"$imagepolicy": "data:staging-eun-pipeline:tag"}
