---
environment: development
region: ue

replicaCount: 1
hpa:
  enabled: false
  cpu: 80
  memory: 80
  maxReplicas: 2

image:
  repository: repository/image
  tag: 1.0.0
  pullPolicy: Always
  automation:
    enabled: true
    interval: 1m0s
    semver:
      expr: 1.0.x

canary:
  enabled: false
  progressDeadlineSeconds: 60
  skipAnalysis: false
  service:
    port: 80
    targetPort: 80
    portDiscovery: false
    gateways:
    - istio-system/istio-ingressgw
    tls:
      mode: DISABLE
    retries:
      attemps: 3
      perTryTimeout: 1s
      retryOn: "gateway-error,connect-failure,refused-stream"
    match:
      prefix: "/"
      rewrite: "/"
  analysis:
    defaultMetrics: true
    interval: 1m
    threshold: 3
    maxWeight: 50
    stepWeight: 10
    metrics: []
    webhooks: []

hosts:
- "*"

imagePullSecrets: [ ]
nameOverride: { }
fullnameOverride: { }

deployment:
  antiaffinity:
    enabled: false

livenessProbe: { }

readinessProbe: { }

ports:
- name: http
  containerPort: 80
  protocol: TCP

service:
  type: ClusterIP
  port: 80
  sslport: 443
  annotations: { }

servicePort: http

ingress:
  enabled: false

virtualService:
  gateways:
  - istio-system/istio-ingressgw
  match:
  - name: default
    prefixes:
    - /
    rewrite: /
    routes:
    - host: app.default.svc.cluster.local
      port: 80
  tcp:
    enabled: false
    match:
    - port: 80
      routes:
      - host: app.default.svc.cluster.local
        port: 80


prometheus:
  enabled: false

annotations: { }

labels: { }

resources: { }

env: { }

addEnv: { }

config: { }

configPath: /config/
configFilename: config.yaml

secrets: { }

certs: { }

certsMountPath: /app/secrets/
certsMountSubPath: { }

nodeSelector: { }

tolerations: [ ]

affinity: { }
