{{- if not .Values.canary.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "api.name" . }}
spec:
  gateways:
    {{- range $gateway := .Values.virtualService.gateways }}
    - {{ $gateway }}
    {{- end }}
  hosts:
    {{- if $.Values.hostsStringArray }}
    {{- $parts := split "," $.Values.hostsStringArray }}

    {{- range $host := $parts }}
    - {{ $host | quote }}
    {{- end -}}

    {{ else }}

    {{- range $host := $.Values.hosts }}
    - {{ $host | quote }}
    {{- end -}}

    {{- end }}
  http:
  {{- range $match := .Values.virtualService.match }}
  - name: {{ $match.name }}
    match:
      {{- range $prefix := $match.prefixes }}
      - uri:
          prefix: {{ $prefix }}
      {{- end }}
    rewrite:
      uri: {{ $match.rewrite }}
  {{- if  $match.headers }}
    headers:
{{ toYaml $match.headers | trim | indent 6}}
  {{- end }}
    route:
      {{- range $route := $match.routes }}
      - destination:
          host: {{ $route.host }}
          port:
            number: {{ $route.port }}
        {{- if $route.subset }}
        subset: {{ $route.subset }}
        {{- end }}
        {{- if $route.weight }}
        weight: {{ $route.weight }}
        {{ else }}
        weight: 100
        {{- end }}
      {{- if $route.corsPolicy }}
        corsPolicy:
{{- toYaml $route.corsPolicy | trim | nindent 10}}
      {{- end }}
      {{- end }}
  {{- end }}

  {{- if .Values.virtualService.tcp.enabled }}
  tcp:
  - match:
  {{- range $match := .Values.virtualService.tcp.match }}
    - port: {{ $match.port }}
    route:
      {{- range $route := $match.routes }}
    - destination:
        host: {{ $route.host }}
        port:
          number: {{ $route.port }}
      {{- if $route.subset }}
      subset: {{ $route.subset }}
      {{- end }}
      {{- if $route.weight }}
      weight: {{ $route.weight }}
      {{ else }}
      weight: 100
      {{- end }}
      {{- if $route.corsPolicy }}
      corsPolicy:
      {{- toYaml $route.corsPolicy | trim | nindent 10}}
      {{- end }}
      {{- end }}
  {{- end }}
  {{- end }}
{{- end}}
