apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: critical
spec:
  releaseName: critical
  serviceAccountName: data
  chart:
    spec:
      chart: charts/api
      sourceRef:
        kind: GitRepository
        name: data
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    name: critical
    image:
      repository: marcoamador/critical
    ports:
    - name: http
      containerPort: 8000
      protocol: TCP
    prometheus:
      enabled: true
    hpa:
      enabled: true
    hosts:
    - critical.data
    canary:
      enabled: true
      analysis:
        webhooks:
        - name: load-test
          type: rollout
          url: http://flagger-loadtester.istio-system/
          timeout: 5s
          metadata:
            type: cmd
            cmd: hey -z 2m -q 10 -c 2 http://critical-canary.data/ping
      service:
        targetPort: 8000
    ingress:
      enabled: false

