apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: critical
spec:
  releaseName: critical
  serviceAccountName: data
  chart:
    spec:
      chart: _charts/api
      sourceRef:
        kind: GitRepository
        name: data
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    name: critical
    image:
      repository: marcoamador/critical
      automation:
        semver:
          expr: 1.x.x
    ports:
    - name: http
      containerPort: 8000
      protocol: TCP
    prometheus:
      enabled: true
    hpa:
      enabled: true
    hosts:
    - critical.data
    canary:
      enabled: true
      analysis:
        # make demo goes faster
        interval: 15s
        webhooks:
        - name: load-test
          type: rollout
          url: http://flagger-loadtester.istio-system/
          timeout: 5s
          metadata:
            type: cmd
            # make demo goes faster
            cmd: hey -z 12s -q 5 -c 2 http://critical-canary.data/loadtest
      service:
        port: 80
        targetPort: 8000
    dark:
      enabled: false
      image:
        repository: marcoamador/critical
        automation:
          semver:
            expr: 2.x.x
      canary:
        enabled: true
        analysis:
          # make demo goes faster
          interval: 15s
          webhooks:
          - name: load-test
            type: rollout
            url: http://flagger-loadtester.istio-system/
            timeout: 5s
            metadata:
              type: cmd
              # make demo goes faster
              cmd: hey -z 12s -q 5 -c 2 http://critical-dark-canary.data/loadtest
        service:
          port: 80
          targetPort: 8000
