apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: critical
spec:
  releaseName: critical
  serviceAccountName: data
  chart:
    spec:
      chart: charts/api
      sourceRef:
        kind: GitRepository
        name: data
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    name: critical
    image:
      repository: marcoamador/critical
    ports:
    - name: http
      containerPort: 8000
      protocol: TCP
    prometheus:
      enabled: true
    hpa:
      enabled: true
    hosts:
    - critical.data
    canary:
      enabled: true
      analysis:
        defaultMetrics: true
        interval: 2m
        maxWeight: 50
        metrics: [ ]
        stepWeight: 10
        threshold: 3
        webhooks:
        - name: load-test
          type: rollout
          url: http://flagger-loadtester.istio-system/
          timeout: 5s
          metadata:
            type: cmd
            cmd: hey -z 2m -q 10 -c 2 http://critical.data/loadtest
      progressDeadlineSeconds: 60
      service:
        match:
          prefix: /critical/
          rewrite: /
          headers:
            request:
              add:
                X-Forwarded-Prefix: "/critical"
          corsPolicy:
            allowMethods:
            - GET
            - PUT
            - POST
            - OPTIONS
            - HEAD
            - DELETE
            - PATCH
            allowHeaders:
            - authorization
            - content-type
            - accept
            - origin
            - user-agent
            allowCredentials: false
            maxAge: "24h"
        port: 80
        retries:
          attemps: 3
          perTryTimeout: 1s
          retryOn: gateway-error,connect-failure,refused-stream
        targetPort: 8000
        portDiscovery: true # set to true when using gRPC
        tls:
          mode: DISABLE
    ingress:
      enabled: false

