apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: echo
spec:
  releaseName: echo
  serviceAccountName: data
  chart:
    spec:
      chart: _charts/api
      sourceRef:
        kind: GitRepository
        name: data
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: marcoamador/echo
      tag: 1.0.0
