apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello
spec:
  releaseName: hello
  serviceAccountName: data
  chart:
    spec:
      chart: _charts/api
      sourceRef:
        kind: GitRepository
        name: data
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    name: hello
    image:
      repository: marcoamador/hello
    ports:
    - name: http
      containerPort: 8000
      protocol: TCP
