apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pipeline-canary
spec:
  releaseName: pipeline-canary
  serviceAccountName: data
  chart:
    spec:
      chart: charts/api
      sourceRef:
        kind: GitRepository
        name: data
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    name: pipeline-canary
    image:
      repository: marcoamador/pipeline
    ports:
    - name: http
      containerPort: 4195
      protocol: TCP
    prometheus:
      enabled: true
    hpa:
      enabled: true
    hosts:
    - pipeline-canary.data
    canary:
      enabled: true
      analysis:
        webhooks:
        - name: load-test
          type: rollout
          url: http://flagger-loadtester.istio-system/
          timeout: 5s
          metadata:
            type: cmd
            cmd: hey -z 2m -q 10 -c 2 http://pipeline-canary-canary.data/ping
      service:
        targetPort: 4195
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
