apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pipeline-canary
spec:
  releaseName: pipelinee-canary
  serviceAccountName: data
  chart:
    spec:
      chart: charts/api
      sourceRef:
        kind: GitRepository
        name: data
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: marcoamador/pipeline
    ports:
    - name: http
      containerPort: 4195
      protocol: TCP
    prometheus:
      enabled: true
    canary:
      enabled: true
      service:
        targetPort: 4195
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
