---
replicaCount: 1

image:
  repository: repository/image
  tag: 1.0.0
  pullPolicy: Always
  automation:
    enabled: true
    interval: 1m0s
    semver:
      expr: 1.0.x

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

deployment:
  antiaffinity:
    enabled: false

livenessProbe: { }

readinessProbe: { }

ports:
- name: http
  containerPort: 80
  protocol: TCP

service:
  type: ClusterIP
  port: 80
  sslport: 443
  annotations: { }

servicePort: http

ingress:
  enabled: false

prometheus:
  enabled: false

annotations: { }

labels: { }

resources: { }

hpa:
  enabled: false

env: { }

addEnv: { }

config: { }

configPath: /config/
configFilename: config.yaml

secrets: { }

certs: { }

certsMountPath: /app/secrets/
certsMountSubPath: { }

nodeSelector: { }

tolerations: [ ]

affinity: { }
