apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: critical
spec:
  values:
    hosts:
    - critical.staging.euw
    - critical.data.svc.cluster.local
    image:
      tag: 1.0.8 # {"$imagepolicy": "data:staging-euw-critical:tag"}
      automation:
        semver:
          expr: x.x.x
